#!/bin/bash
ip link set dev eth2 up
ip a a 31.4.255.97/27 dev eth2
ip link set dev eth0 up
ip a a 31.4.255.130/27 dev eth0
ip link set dev eth1 up
ip a a 31.4.255.193/27 dev eth1

#ip r a 31.4.255.0/27 via 31.4.255.98
#ip r a 31.4.255.32/27 via 31.4.255.98
#ip r a 31.4.255.64/27 via 31.4.255.129
#ip r a 31.4.255.160/27 via 31.4.255.129

service quagga start
sleep 1
#filtrage
iptables -P INPUT DROP
iptables -P OUTPUT DROP
iptables -P FORWARD DROP

#autorisation le ping
iptables -t filter -A OUTPUT -p icmp -j ACCEPT
iptables -t filter -A INPUT -p icmp -j ACCEPT
iptables -t filter -A FORWARD -p icmp -j ACCEPT

#autorisation le ping
iptables -A OUTPUT -p udp --dport 520 -j ACCEPT
iptables -A INPUT -p udp --dport 520 -j ACCEPT
iptables -A FORWARD -p udp --dport 520 -j ACCEPT

#autoriser dns
iptables -t filter -A FORWARD -d 31.4.255.194/27 -p udp --dport 53 -j ACCEPT
iptables -t filter -A FORWARD -s 31.4.255.194/27 -p udp --sport 53 -j ACCEPT

#autoriser http
iptables -t filter -A FORWARD -d 31.4.255.162/27 -p tcp --dport 80 -j ACCEPT
iptables -t filter -A FORWARD -s 31.4.255.162/27 -p tcp --sport 80 -j ACCEPT
