/**
 */
package calcul.provider;

import calcul.util.CalculAdapterFactory;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class CalculItemProviderAdapterFactory extends CalculAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public CalculItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link calcul.Calcul} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CalculItemProvider calculItemProvider;

	/**
	 * This creates an adapter for a {@link calcul.Calcul}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCalculAdapter() {
		if (calculItemProvider == null) {
			calculItemProvider = new CalculItemProvider(this);
		}

		return calculItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link calcul.SortieOperateur} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SortieOperateurItemProvider sortieOperateurItemProvider;

	/**
	 * This creates an adapter for a {@link calcul.SortieOperateur}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSortieOperateurAdapter() {
		if (sortieOperateurItemProvider == null) {
			sortieOperateurItemProvider = new SortieOperateurItemProvider(this);
		}

		return sortieOperateurItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link calcul.PortSortie} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PortSortieItemProvider portSortieItemProvider;

	/**
	 * This creates an adapter for a {@link calcul.PortSortie}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPortSortieAdapter() {
		if (portSortieItemProvider == null) {
			portSortieItemProvider = new PortSortieItemProvider(this);
		}

		return portSortieItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link calcul.PortEntree} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PortEntreeItemProvider portEntreeItemProvider;

	/**
	 * This creates an adapter for a {@link calcul.PortEntree}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPortEntreeAdapter() {
		if (portEntreeItemProvider == null) {
			portEntreeItemProvider = new PortEntreeItemProvider(this);
		}

		return portEntreeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link calcul.EntreeOperateur} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EntreeOperateurItemProvider entreeOperateurItemProvider;

	/**
	 * This creates an adapter for a {@link calcul.EntreeOperateur}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEntreeOperateurAdapter() {
		if (entreeOperateurItemProvider == null) {
			entreeOperateurItemProvider = new EntreeOperateurItemProvider(this);
		}

		return entreeOperateurItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link calcul.OperateurBinaire} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected OperateurBinaireItemProvider operateurBinaireItemProvider;

	/**
	 * This creates an adapter for a {@link calcul.OperateurBinaire}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createOperateurBinaireAdapter() {
		if (operateurBinaireItemProvider == null) {
			operateurBinaireItemProvider = new OperateurBinaireItemProvider(this);
		}

		return operateurBinaireItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link calcul.OperateurUnaire} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected OperateurUnaireItemProvider operateurUnaireItemProvider;

	/**
	 * This creates an adapter for a {@link calcul.OperateurUnaire}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createOperateurUnaireAdapter() {
		if (operateurUnaireItemProvider == null) {
			operateurUnaireItemProvider = new OperateurUnaireItemProvider(this);
		}

		return operateurUnaireItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link calcul.EntreeConstanteInt} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EntreeConstanteIntItemProvider entreeConstanteIntItemProvider;

	/**
	 * This creates an adapter for a {@link calcul.EntreeConstanteInt}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEntreeConstanteIntAdapter() {
		if (entreeConstanteIntItemProvider == null) {
			entreeConstanteIntItemProvider = new EntreeConstanteIntItemProvider(this);
		}

		return entreeConstanteIntItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link calcul.EntreeConstanteString} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EntreeConstanteStringItemProvider entreeConstanteStringItemProvider;

	/**
	 * This creates an adapter for a {@link calcul.EntreeConstanteString}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEntreeConstanteStringAdapter() {
		if (entreeConstanteStringItemProvider == null) {
			entreeConstanteStringItemProvider = new EntreeConstanteStringItemProvider(this);
		}

		return entreeConstanteStringItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link calcul.EntreeConstanteBool} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EntreeConstanteBoolItemProvider entreeConstanteBoolItemProvider;

	/**
	 * This creates an adapter for a {@link calcul.EntreeConstanteBool}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEntreeConstanteBoolAdapter() {
		if (entreeConstanteBoolItemProvider == null) {
			entreeConstanteBoolItemProvider = new EntreeConstanteBoolItemProvider(this);
		}

		return entreeConstanteBoolItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link calcul.EntreeConstanteFloat} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EntreeConstanteFloatItemProvider entreeConstanteFloatItemProvider;

	/**
	 * This creates an adapter for a {@link calcul.EntreeConstanteFloat}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEntreeConstanteFloatAdapter() {
		if (entreeConstanteFloatItemProvider == null) {
			entreeConstanteFloatItemProvider = new EntreeConstanteFloatItemProvider(this);
		}

		return entreeConstanteFloatItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void dispose() {
		if (calculItemProvider != null) calculItemProvider.dispose();
		if (sortieOperateurItemProvider != null) sortieOperateurItemProvider.dispose();
		if (portSortieItemProvider != null) portSortieItemProvider.dispose();
		if (portEntreeItemProvider != null) portEntreeItemProvider.dispose();
		if (entreeOperateurItemProvider != null) entreeOperateurItemProvider.dispose();
		if (operateurBinaireItemProvider != null) operateurBinaireItemProvider.dispose();
		if (operateurUnaireItemProvider != null) operateurUnaireItemProvider.dispose();
		if (entreeConstanteIntItemProvider != null) entreeConstanteIntItemProvider.dispose();
		if (entreeConstanteStringItemProvider != null) entreeConstanteStringItemProvider.dispose();
		if (entreeConstanteBoolItemProvider != null) entreeConstanteBoolItemProvider.dispose();
		if (entreeConstanteFloatItemProvider != null) entreeConstanteFloatItemProvider.dispose();
	}

}
